[feat] Add monitors API
tasima-uniritter/pda-a-monitors pull request #14
Opened 2018-06-27 04:49 UTC by hyanmandian

2018-06-27 13:32 UTC, pezzetti commented on src/main/java/br/edu/uniritter/monitors/service/MonitorService.java
> +    public Monitor store(Monitor monitor) {
Não seria melhor renomear para save ?

2018-06-27 17:55 UTC, luiscoms commented on src/main/java/br/edu/uniritter/monitors/api/ExceptionHandling.java
> +import javassist.tools.web.BadHttpRequest;
Não está sendo usado

2018-06-27 17:57 UTC, luiscoms requested changes

2018-06-27 17:57 UTC, luiscoms commented on src/main/java/br/edu/uniritter/monitors/api/ExceptionHandling.java
> +import javassist.tools.web.BadHttpRequest;
Não está sendo usado

2018-06-27 17:57 UTC, luiscoms commented on src/main/java/br/edu/uniritter/monitors/service/MonitorService.java
> +    public Monitor store(Monitor monitor) {
Concordo

2018-06-28 12:58 UTC, hyanmandian commented on src/main/java/br/edu/uniritter/monitors/service/MonitorService.java
> +    public Monitor store(Monitor monitor) {
qual é a diferença de save e store?

2018-06-28 12:58 UTC, hyanmandian commented on src/main/java/br/edu/uniritter/monitors/api/ExceptionHandling.java
> +import javassist.tools.web.BadHttpRequest;
true, vou remover

2018-06-28 13:37 UTC, luiscoms approved these changes

2018-06-28 13:38 UTC, merged